### ISSUE TITLE
Scratching an image with alpha channel doesn't completely remove the mask

### ISSUE THREAD

**Issue by Azlond** [joehour/ScratchCard#14]
Hi Joe,

when scratching a coupon-image that uses an alpha-channel, it's only possible to scratch the areas with no transparency. When scratching over a transparent area, the mask stays there; it does however count correctly towards the scratchPercent.

[Sample Image](https://raw.githubusercontent.com/Azlond/TravelDiscovery/master/TravelDiscovery/TravelDiscovery/Assets.xcassets/Countries/USA.imageset/USA.png)
[Scratched Sample](https://i.imgur.com/IkvAE7p.png)

This used to work fine in 1.0.15, so it must have been a regression in the last two committs.

**Comment by joehour** [comment]
Hi, Jan
After 1.0.15 version, I change the scratch mode because of lag problem on iOS 10 device~
So the coupon transparent area will cause this problem~
A good way to solve this problem is to change transparent pixel to white pixel.

Hence, I add processPixels method to solve this issue~
You can find code in master branch, or update it by CocoaPods(ver 1.1.3)~

**Comment by Azlond** [comment]
Hi Joe,

this solved it! Thank you very much for your help.

Jan
